services:
  default:
    # Name the image.
    image: vlc-android
    build: .
    # Mount the entire repository so all code and changes are visible for building
    # and to allow the output files.
    volumes:
      - type: bind
        source: .
        target: /vlc-android
